name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nestjs_prod:green .
    
      - name: Save and compress Docker image
        run: |
          docker save nestjs_prod:green | gzip > nestjs_prod.tar.gz
      
      - name: Copy image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "nestjs_prod.tar.gz"
          target: "/tmp"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ vars.URL }}
    steps:
    - name: Deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          ./deploy.sh prod
